# K-NN

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, classification_report


## KNN Classifier 

In [7]:
df_iris = pd.read_csv("iris.data",header=None)
df_iris.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [3]:
X= df_iris.iloc[:, :-1]
y = df_iris.iloc[:, -1]
y.head()
y.value_counts(dropna=False)

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: 4, dtype: int64

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.3, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((105, 4), (45, 4), (105,), (45,))

In [9]:
knn_class = KNeighborsClassifier(n_neighbors = 3)
knn_class.fit(X_train, y_train)
y_predicted = knn_class.predict(X_test)
#print(y_predicted)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_predicted),'\n')    #ko in ra nhãn lớp
print(confusion_matrix(y_test, y_predicted, labels=['Iris-setosa','Iris-versicolor','Iris-virginica']),'\n')
    
acc_ = accuracy_score(y_test, y_predicted)*100
print ('accuracy_score:')
print (acc_,'\n')

print("Precision")
print(precision_score(y_test, y_predicted,labels=['Iris-setosa','Iris-versicolor','Iris-virginica'],average=None)*100,'\n')
    
print("Recall")
print(recall_score(y_test, y_predicted,average=None),'\n')
print("F1 score")
print(f1_score(y_test, y_predicted,average=None),'\n')

print(classification_report(y_test, y_predicted))



Confusion Matrix:
[[15  0  0]
 [ 0 15  0]
 [ 0  2 13]] 

[[15  0  0]
 [ 0 15  0]
 [ 0  2 13]] 

accuracy_score:
95.55555555555556 

Precision
[100.          88.23529412 100.        ] 

Recall
[1.         1.         0.86666667] 

F1 score
[1.         0.9375     0.92857143] 

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       0.88      1.00      0.94        15
 Iris-virginica       1.00      0.87      0.93        15

       accuracy                           0.96        45
      macro avg       0.96      0.96      0.96        45
   weighted avg       0.96      0.96      0.96        45

